Fix AttributeError for Python >=3.8
Importing `importlib` and then making calls like `importlib.util.*` causes `AttributeError: module 'importlib' has no attribute 'util'` in Python 3.8 and higher. I've encountered this for 3.8 myself and there is a bug report for 3.9: https://bugs.python.org/issue41958. The solution is to import `importlib.shutil` explicitly. This change doesn't break anything in older versions of Python.